import TheoryLib.PiQuantitativeBlockHitting.T122T122WeightedActiveSupportSeparator

#print axioms Theory.PiDigits.WeightedNaturalScaleFrontier.jacksonWeightedFourierLoad_le_four_mul_of_active_bound
#print axioms Theory.PiDigits.WeightedNaturalScaleFrontier.active_exact_finite_frequency_hypothesis_implies_weighted
#print axioms Theory.PiDigits.WeightedNaturalScaleFrontier.weighted_finite_frequency_hypothesis_strict_vs_active_exact
